stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy
  

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  image: node:latest
  script:
    - npm install
    - CI=false npm run build #pour enlever les warning jaune utilser CI= false
    

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  image: node:latest
  before_script:
    - npm install
  script:
    - npm run test:ci
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    paths:
      - coverage/
    when: always
    reports:
      junit:
        - junit.xml 


deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."